# Generated by Django 6.0.4 on 2026-04-30 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow'),
        ),
        migrations.AddField(
            model_name='jobdownload',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobmessage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobstep',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobvalue',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'submitted_at'], name='jobs_status_bf943a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user', 'status'], name='jobs_user_id_443e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['workflow', 'status'], name='jobs_workflo_75110d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jobstep',
            unique_together={('job', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='jobvalue',
            unique_together={('job', 'parameter_id', 'is_input')},
        ),
    ]
