# Generated by Django 6.0.4 on 2026-04-30 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Workflow Categories',
                'db_table': 'workflow_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('yaml_config', models.TextField(help_text='YAML configuration for the workflow')),
                ('nextflow_script', models.TextField(blank=True, help_text='Path to the Nextflow script')),
                ('config_file', models.TextField(blank=True, help_text='Path to the Nextflow config file')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('maintenance', 'Maintenance')], default='enabled', max_length=20)),
                ('public', models.BooleanField(default=False, help_text='Publicly accessible to all users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups that can access this workflow', to='auth.group')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowcategory')),
            ],
            options={
                'db_table': 'workflows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('logs', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow')),
            ],
            options={
                'db_table': 'workflow_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('parameter_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder'), ('text', 'Text'), ('number', 'Number'), ('checkbox', 'Checkbox'), ('list', 'List'), ('textarea', 'Textarea')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.TextField(blank=True)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('is_input', models.BooleanField(default=True)),
                ('is_output', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='workflows.workflow')),
            ],
            options={
                'db_table': 'workflow_parameters',
                'ordering': ['order', 'name'],
                'unique_together': {('workflow', 'parameter_id')},
            },
        ),
    ]
