# Generated by Django 6.0.4 on 2026-05-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='env_vars',
            field=models.TextField(blank=True, help_text='Environment variables (written to nextflow.env)'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='nextflow_config',
            field=models.TextField(blank=True, help_text='Nextflow configuration (written to nextflow.config)'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='nextflow_profile',
            field=models.CharField(blank=True, help_text='Nextflow profile to use', max_length=255),
        ),
        migrations.AddField(
            model_name='workflow',
            name='working_directory',
            field=models.TextField(blank=True, help_text='Working directory for Nextflow execution'),
        ),
    ]
